feat: update ocean buttons
ocean-ds/ocean-android pull request #533
Opened 2024-01-03 16:33 UTC by fernandozanutto

## Description

Update paddings and sizes

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Screenshots (if appropriate):

## Checklist:

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) document
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have made corresponding changes to the documentation (if appropriate)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All new and existing tests passed

2024-01-03 17:28 UTC, nordael requested changes

2024-01-03 17:28 UTC, nordael commented on ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanButton.kt
> +                    println("Botão clicado")
Usa 
`val context = LocalContext.current`
Daí no onClick:
```
Toast.makeText(
            context
            "Alert Action",
             Toast.LENGTH_SHORT
 ).show()
```

2024-01-03 18:01 UTC, fernandozanutto commented on ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanButton.kt
> +                    println("Botão clicado")
Acredito que pra essa caso é desnecessário, o callback do click veio junto no ctrl c ctrl v, botei ele qnd construi os componentes só pra testar os clicks, hoje nem sao mais necessários

2024-01-04 14:51 UTC, FariasBlu approved these changes

2024-01-04 15:00 UTC, nordael approved these changes

2024-01-04 15:00 UTC, merged